# background_opacity 0.8

include ./Catppuccin-Macchiato.conf

copy_on_select yes

map cmd+c        copy_to_clipboard
map cmd+v        paste_from_clipboard

# Window management
map ctrl+shift+n  new_os_window_with_cwd
map alt+q  close_window
map ctrl+shift+f3 set_tab_title 
map alt+t  new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd
map alt+.        next_window
map alt+,        previous_window
map alt+shift+. next_tab
map alt+shift+, previous_tab

font_size 13
font_family BlexMono Nerd Font

shell_integration  no-cursor
cursor_shape block

# window_padding_width 5
