[general]
# import = ["~/.config/alacritty/aura-theme.toml"]

[window]
opacity = 0.9
# padding = { x = 20, y = 20 }
decorations = "full"
# blur = true

[font]
size = 13
normal = { family = "BlexMono Nerd Font" } 

