theme = "autumn_night"

[editor]
bufferline = "always"
line-number = "relative"
cursorline=true

[keys.normal]
S-l = ":buffer-next"
S-h = ":buffer-previous"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

